# docker-compose.yml
version: '3.8'

services:
  web:
    build: .
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; cd sql_app; uvicorn main:app --host 0.0.0.0'
    volumes:
      - .:/app
    ports:
      - 80:8000
    environment:
      - DATABASE_URL=postgresql://fastapi_app:fastapi_app@db:5432/fastapi_app
      - HOST_URL=http://127.0.0.1:80
    depends_on:
      - db
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    environment:
      - POSTGRES_USER=fastapi_app
      - POSTGRES_PASSWORD=fastapi_app
      - POSTGRES_DB=fastapi_app

volumes:
  postgres_data: